# Generated by Django 5.0.1 on 2024-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_management', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
